name: Motuo CI

on: push

jobs:
  build-apk:
    name: build apk
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'build:')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.5"
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk

      - uses: dart-lang/setup-dart@v1
      - run: dart --version
      - run: dart run deploy.dart dart-task

      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ secrets.CDAPK }}
<<<<<<< HEAD
          repository-name: laof/blob
          target-folder: flutter-apk
=======
          repository-name: laof/laof.github.io
          target-folder: app
>>>>>>> 605a78e130bb0417047f8eb04af0b96a214f145a
          branch: main
          commit-message: added motuo.apk by github action
          folder: app
