name: Motuo

on: push

jobs:
  build:
    name: build apk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.5'
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build apk

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.5'
        architecture: x64
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
